version: '3.7'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - DEBUG=1
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - ./localstack/temp/localstack:/var/lib/localstack
      - ./localstack/var/run/docker.sock:/var/run/docker.sock
      - ./init-dynamodb.sh:/docker-entrypoint-initaws.d